version: '3'

services:
  db:
    container_name: notifications-db
    image: postgres:13.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # Скрипт для инициализации таблицы в БД
      - ./src/db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - '5672:5672'
      - '15672:15672'
